// Types for `import photo from './x.jpg'` (next/image static imports).
// next-env.d.ts normally supplies these, but it is git-ignored and only
// generated by `next dev`/`next build` -- CI type-checks before it builds.
/// <reference types="next/image-types/global" />
